/* GENERATED BY scripts/gen-tokens.mjs. DO NOT EDIT.
 *
 * Every colour token in src/app/globals.css that is an oklch literal, converted to sRGB hex.
 *
 * WHAT THIS IS FOR. Two kinds of consumer cannot read a CSS custom property and so need a hex:
 * an ImageResponse (src/app/opengraph-image.tsx, icon.tsx, apple-icon.tsx) renders in satori with
 * no stylesheet and no cascade, and a themeColor viewport export is read by the browser chrome.
 * Both used to hold hand-converted literals. All four in opengraph-image.tsx were stale leftovers
 * of the cream palette deleted on 2026-08-09, which is why this file exists rather than a comment
 * asking people to keep them in sync.
 *
 * To change a colour, change the token in globals.css and run: node scripts/gen-tokens.mjs
 * `pnpm build` runs --check and fails on a stale file, so this cannot drift from the palette.
 *
 * Tokens that are not oklch literals are absent by design, because they are not convertible and no
 * consumer needs them: --card-foreground, --popover-foreground, --secondary-foreground, --accent-foreground, --border-strong, --radius, --measure, --gap.
 */

export const LIGHT = {
  '--background': '#fdfdfc',
  '--foreground': '#141412',
  '--card': '#ffffff',
  '--popover': '#ffffff',
  '--primary': '#141412',
  '--primary-foreground': '#fcfcfc',
  '--secondary': '#f2f2f0',
  '--muted': '#f2f2f0',
  '--muted-foreground': '#72726f',
  '--accent': '#f0f0ef',
  '--destructive': '#be2323',
  '--signal': '#007142',
  '--border': '#dddcda',
  '--input': '#dddcda',
  '--ring': '#72726f',
} as const;

export const DARK = {
  '--background': '#0e0d0b',
  '--foreground': '#efeeed',
  '--card': '#161614',
  '--popover': '#161614',
  '--primary': '#efeeed',
  '--primary-foreground': '#0e0d0b',
  '--secondary': '#242422',
  '--muted': '#242422',
  '--muted-foreground': '#93928f',
  '--accent': '#242422',
  '--destructive': '#e85854',
  '--signal': '#37c080',
  '--border': '#ffffff1f',
  '--input': '#ffffff29',
  '--ring': '#81807e',
} as const;

export type ColourToken = keyof typeof LIGHT;
