export const metadata = {
  alternates: { canonical: '/work/themoment' },
  title: 'The Moment',
  description: 'Storefront, checkout and admin for a Calgary bakery, and the decision that kept the data worth having.',
};

/* This page said "154 real ones had gone through it", meaning the storefront. That was false, and
 * it was live for about an hour on 2026-08-16 before a reviewer reading the actual export caught it.
 *
 * themoment/sales/exports/orders-raw.json has 154 order records, and their Square `source.name`
 * splits 135 with no source (in-person at markets), 17 "Payment Links" (generated by hand), and 2
 * "The Moment Orders", which is the app. themoment/INDEX.md and strategy/online-growth-evaluation
 * -2026-07-13.md both say it plainly: one real online order since going live on 2 July.
 *
 * The claim came from CareerOS/strategy/project-evidence-ledger.md, which conflates a count of
 * orders in the bakery's Square ACCOUNT with a count of orders through the software. That line has
 * been corrected at source. Do not reintroduce a throughput number here without opening the export
 * and reading `source.name`.
 */
export default function TheMomentPage() {
  return (
    <>
      <h1>The Moment</h1>
      <p className="lede">
        A bakery in Calgary. I built the storefront people order from, the checkout that takes the
        money, and the back office behind both.
      </p>

      <dl className="facts">
        <div>
          <dt>What</dt>
          <dd>Ordering, payment, and an admin for the day&apos;s orders</dd>
        </div>
        <div>
          <dt>Live at</dt>
          <dd><a href="https://themomentyyc.com" target="_blank" rel="noreferrer">themomentyyc.com</a></dd>
        </div>
        <div>
          <dt>Stack</dt>
          <dd>Next.js, Sanity for the content, Supabase for the orders, Square for payment</dd>
        </div>
        <div>
          <dt>Orders</dt>
          <dd>
            <span className="tnum">154</span> through July 2026, nearly all of them taken in person
            at markets. The online store opened that month and has taken one
          </dd>
        </div>
      </dl>

      <h2 className="sec">What I actually did</h2>
      <p className="body">
        I did the discovery first, because a bakery does not want a website, it wants the mornings
        to go smoothly. So the questions were about the mornings: what gets ordered, what runs out,
        who has to be told, and what happens when someone wants something the kitchen cannot make
        that day. The answers are what the software is shaped around.
      </p>
      <p className="body">
        Then requirements, the build direction, and the checking. I am the one who decides what
        exists and whether what got built is right; the code gets written fast and it gets written
        wrong unless somebody is holding the line on what it was for. That is the same job I did for
        eight years between an insurer&apos;s business and its engineers. The difference now is that
        there is no separate team to hand it to, so I build it as well as specify it.
      </p>

      <div className="decision">
        <span className="k">The decision that mattered</span>
        <p>
          Square handles the payment, and it was tempting to let Square handle the order too, since
          it will. I kept the orders in a database the business owns and used Square only for taking
          money.
        </p>
        <p>
          The reason is what happens later. An order that lives inside a payment provider can be read
          and refunded and very little else. An order in a table you own can be counted, filtered,
          chased, reported on, and moved somewhere else the day the provider stops suiting you. Every
          question anyone has since put to that data has been answerable because of one choice made
          before there was any data, and not one of those questions had been thought of at the time.
        </p>
      </div>

      <h2 className="sec">What I would say about it honestly</h2>
      <p className="body">
        It is a small shop, this is a small system, and it has not been busy. The online store opened
        in July and has taken one real order. Almost everything the bakery sells still goes over a
        table at a market, which is a fact about the shop rather than about the software, but it is
        the fact that matters: nobody has proved yet that the people who buy the bread want to buy it
        this way. What the build proves is narrower. It runs unattended, it takes a real payment from
        a real card, and it is still standing months later, which is the part most of these do not
        survive.
      </p>
    </>
  );
}
