import type { Metadata } from 'next';
import facts from '../../../../content/work/site-facts.json';
import shots from '../../../../content/work/shots.json';

/* HOW THIS SITE IS BUILT. G1 of the 2026-09-04 audit, and his ruling on which shape it takes.
 *
 * THE PROBLEM IT SOLVES. The hub is eight rows of live sentences and that design is right: it shows
 * state rather than link labels. It is also the reason a stranger has no idea the cook screen
 * exists, or that a recipe cannot ship unless every number in a step appears in the source that
 * step quotes. The audit put it plainly: "The engineering under this site is unusually good and
 * almost none of it is visible to the person it is meant to impress." Nowhere on the site was there
 * a picture of the site.
 *
 * EVERY NUMBER ON THIS PAGE IS COUNTED, NOT TYPED. `scripts/gen-site-facts.mjs` reads the repo and
 * writes `content/work/site-facts.json`, and `pnpm build` runs its `--check`. That is not decoration
 * on a page about gates: a page boasting "6 build gates" while the build runs 11 would be the worst
 * file in this repo, and the failure is not hypothetical. AGENTS.md's own surfaces table lost track
 * of five routes for weeks. /reading/about printed a typed "33" while the table held 55. The share
 * card rendered in a palette that had been deleted a month earlier, under a comment insisting it
 * mirrored the current one. Every one of those was a hand-kept number.
 *
 * CLAUSE 7(c) APPLIES HERE, as it does to every page under /work and nowhere else on the site.
 * These are the only pages that could read as advertising availability for outside work while an
 * immigration file is pending. There is no availability claim on this page, no rates, no invitation
 * to get in touch about work, and there must not be one. Read work-permit/CLAUDE.md before adding a
 * sentence. This page describes a thing that exists; it does not offer anything.
 */

export const metadata: Metadata = {
  title: 'How this site is built',
  description:
    'The engineering behind hoodii.studio: what the build refuses to ship, and why every number on the page is counted rather than typed.',
  alternates: { canonical: '/work/site' },
};

/* A shot older than this says so on the page. Not a gate: a screenshot cannot be regenerated by a
 * build container, so the honest move is the one HealthOS/CURRENT.md makes with a stale weight,
 * which is to keep showing it and say how old it is. */
const STALE_AFTER_DAYS = 30;

function daysSince(iso: string): number {
  const then = Date.parse(`${iso}T00:00:00Z`);
  if (Number.isNaN(then)) return 0;
  return Math.floor((Date.now() - then) / 86_400_000);
}

export default function WorkSite() {
  return (
    <>
      <h1>How this site is built</h1>
      <p className="lede">
        This site is {facts.apps} surfaces I use most days, and the interesting part is not the
        pages. It is what the build refuses to ship.
      </p>

      <h2 className="sec">What is here</h2>
      <p className="body">
        {facts.pages} pages and {facts.endpoints} endpoints, across {facts.apps} top-level surfaces
        that each carry their own layout and stylesheet. {facts.recipes} recipes written out step by
        step. {facts.agentsLines} lines of notes explaining why things are the way they are, which is
        longer than most of the code it describes and is the file I actually maintain.
      </p>
      <p className="body">
        Every figure in that paragraph is counted from the repository when the site is built. If one
        of them stops being true, the deploy fails rather than the sentence going quietly wrong.
        That is the whole idea of the place, applied to the page describing it.
      </p>

      <h2 className="sec">What it looks like</h2>
      <p className="body">
        All four are phone screens, because the phone is what these are for: a kitchen counter, a
        squat rack, a pool deck.
      </p>

      <div className="shots">
        {shots.map((s, i) => {
          const age = daysSince(s.takenAt);
          return (
            <figure className="shot" key={s.id}>
              {/* Explicit dimensions so the page does not jump as each one arrives, and lazy on
                  everything below the first: four screenshots of a text UI are the heaviest thing
                  on this site and only the top one is visible on arrival. Plain img rather than
                  next/image for the reason the rest of this repo gives: the transform allowance is
                  not worth spending on static assets that are already the right size. */}
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={s.src}
                alt={s.label}
                width={s.width}
                height={s.height}
                loading={i === 0 ? 'eager' : 'lazy'}
                decoding="async"
              />
              <figcaption>
                <span className="shot-label">{s.label}</span>
                <span className="shot-caption">{s.caption}</span>
                <span className="shot-meta">
                  {s.path}, {s.takenAt} at {s.commit}
                  {age > STALE_AFTER_DAYS && (
                    <span className="shot-stale">
                      {' '}
                      This one is {age} days old and the page may have moved on.
                    </span>
                  )}
                </span>
              </figcaption>
            </figure>
          );
        })}
      </div>

      <h2 className="sec">What the build refuses</h2>
      <p className="body">
        {facts.buildGates} checks run before the site compiles, and any one of them stops a deploy.
        They are not style rules. Each exists because something specific went wrong once and I did
        not want to rely on remembering it.
      </p>
      <p className="body">
        A recipe step cannot contain a number that does not appear in the published recipe it quotes.
        No colour can be written anywhere except the one file that defines the palette, and no token
        can be used as a text colour if it is the colour of the paper. The password check exists in
        exactly one place and a second copy fails the build. A write endpoint that is not declared
        in the test harness fails the build, because otherwise a test posts into my actual training
        log.
      </p>
      <p className="finding">
        The rule behind all of them: a rule that does not execute is decoration. Before writing one
        down I have to name the thing that enforces it, or it does not get written down.
      </p>
      <p className="body">
        On top of that, {facts.testSuites} test suites, all {facts.testSuitesWiredIntoVerify} of them
        wired into the one command I run before pushing. Several exist because the gate they cover
        had only ever been seen to pass, and a gate that has only been seen to pass has not been
        seen to work. More than one of them found a hole in the thing it was written to check, on
        its first run.
      </p>

      <h2 className="sec">What I got wrong</h2>
      <p className="body">
        The first dish I ever cooked from the kitchen app burnt. It had passed a six-source check on
        every quantity, a full read of all eighteen rendered steps, and a clean validator. All four
        failures were gaps between the numbers, and every one came from a sentence the model wrote
        rather than a figure a source gave. The fix was not more checking. It was that the software
        is no longer allowed to write cooking steps at all.
      </p>
      <p className="body">
        That is the pattern I keep finding. The expensive defects are not wrong values, they are
        absences and stale copies: a figure that was correct when it was written down and is now a
        second copy of something that moved. Most of what is described above is machinery for
        deleting copies.
      </p>

      <p className="body">
        The code is public. There is a link to the repository in the footer of every page.
      </p>
    </>
  );
}
