import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.GYM_DATABASE_URL);
const sat = await sql`select date, kind, minutes from health_watch_session where date::date >= '2026-01-01' and extract(dow from date::date)=6 order by date`;
console.log('SATURDAYS_2026_rows', sat.length); console.log(JSON.stringify(sat));
const satd = await sql`select count(distinct date::date) d from health_watch_session where date::date >= '2026-01-01' and extract(dow from date::date)=6`;
console.log('SAT_DISTINCT_DAYS', JSON.stringify(satd));
const satk = await sql`select kind, count(*) c from health_watch_session where date::date >= '2026-01-01' and extract(dow from date::date)=6 group by kind order by c desc`;
console.log('SAT_KINDS', JSON.stringify(satk));
const satStrength = await sql`select count(distinct date::date) d from health_watch_session where date::date >= '2026-01-01' and extract(dow from date::date)=6 and kind='strength'`;
console.log('SAT_STRENGTH_DAYS', JSON.stringify(satStrength));
const wk = await sql`select to_char(date_trunc('week', date::date),'YYYY-MM-DD') wk, count(distinct date::date) days from health_watch_session where date::date >= '2026-01-01' group by 1 order by 1`;
const five = wk.filter(r=>Number(r.days)>=5);
console.log('WEEKS_TOTAL', wk.length, 'WEEKS_5PLUS', five.length, JSON.stringify(five));
const dist = {}; for (const r of wk) dist[r.days]=(dist[r.days]||0)+1; console.log('DAYS_PER_WEEK_DIST', JSON.stringify(dist));
const dow = await sql`select extract(dow from date::date) dow, count(distinct date::date) days from health_watch_session where date::date >= '2026-01-01' group by 1 order by 1`;
console.log('DOW_2026', JSON.stringify(dow));
const evening = await sql`select count(*) n, sum(case when (start_time::timestamptz at time zone 'America/Edmonton')::time >= '18:00' then 1 else 0 end) evening, sum(case when (start_time::timestamptz at time zone 'America/Edmonton')::time < '09:00' then 1 else 0 end) morning from health_watch_session where kind='swimming' and date::date >= '2026-06-01'`;
console.log('SWIM_TIME_OF_DAY_since_June', JSON.stringify(evening));
const sample = await sql`select start_time, date, kind from health_watch_session where date::date >= '2026-08-20' order by start_time limit 12`;
console.log('SAMPLE', JSON.stringify(sample));
const lastSwims = await sql`select date, start_time, minutes from health_watch_session where kind='swimming' order by start_time desc limit 25`;
console.log('LAST25SWIMS', JSON.stringify(lastSwims));
const sameDay = await sql`with s as (select date::date d from health_watch_session where kind='swimming' and date::date>='2026-06-01'), l as (select date::date d from health_watch_session where kind='strength' and date::date>='2026-06-01') select (select count(distinct d) from s) swims, (select count(distinct d) from s where d in (select d from l)) swim_on_lift_day`;
console.log('SWIM_ON_LIFT_DAY', JSON.stringify(sameDay));
const notes = await sql`select id, created_at, day, text from gym_note order by created_at desc limit 45`;
console.log('NOTES', JSON.stringify(notes));
