import { getSummary, getRecentPlays, getLatestTops, getListening, type TopSnap } from '@/lib/music/db';
import { AlbumWall, ArtistBars, ListeningClock, MinutesPerDay } from './Charts';
import { TIME_RANGES, RANGE_LABEL } from '@/lib/music/spotify';
import { shortDate, timeAgo } from '@/lib/format';
import { dayOf, daysAgo } from '@/lib/day';
import Readout from '@/components/Readout';
import NowPlaying from '@/components/NowPlaying';

/* ISR, regenerated by /api/music/sync after every good run and otherwise hourly. It was
 * force-dynamic with a Spotify now-playing fetch on the server, which minted a token and woke Neon on
 * every request. Now-playing is the client component the hub footer uses (it fetches /api/spotify
 * itself), so it stays live while the rest is cached. Not 300: Neon bills awake time with a 5-minute
 * floor, so a 300-second window keeps the database awake under any traffic. */
export const revalidate = 3600;

export const metadata = {
  title: 'Music',
  description: 'What I listen to.',
  alternates: { canonical: '/music' },
};

/* The honest-states rule, applied to the hardest case on this site.
 *
 * This page reads a store that holds only what a scheduled job managed to catch. Spotify returns
 * the last 50 plays and nothing else, ever, so the history BEGINS the day collection began, and
 * any framing that implies otherwise is a lie the page tells confidently. Hence the "since" date on
 * the stat and the window printed on every picture.
 *
 * Spotify's top charts are the opposite case: Spotify computes those over its own windows from its
 * own complete record, so they legitimately reach back further than this table does. They stay
 * folded and apart from the pictures. */

/* The short line for a failed run. The full message (with the re-auth steps) stays in music_sync
 * and the cron's log; the page only needs to say which kind of broken it is. */
function failureLabel(error: string): string {
  return /token refresh failed|are not all set/.test(error)
    ? 'Spotify needs signing in again.'
    : 'The last run failed.';
}

function lastDays(n: number): string {
  return n === 1 ? 'last day' : `last ${n} days`;
}

/* One row of the collected history. */
function Play(p: { playedAt: string; trackName: string; trackUrl: string | null; artistName: string; albumName: string | null }) {
  return (
    <div className="play" key={p.playedAt}>
      <div className="pwhen tnum">{timeAgo(p.playedAt)}</div>
      <div className="pbody">
        <div className="ptrack">
          {p.trackUrl ? (
            <a href={p.trackUrl} target="_blank" rel="noreferrer">{p.trackName}</a>
          ) : (
            p.trackName
          )}
        </div>
        <div className="pmeta">
          {p.artistName}
          {p.albumName && <><span className="dot">·</span>{p.albumName}</>}
        </div>
      </div>
    </div>
  );
}

/* One of Spotify's two chart blocks. The snapshot date prints beside the range once it is older
 * than a day, because a failed top fetch keeps the previous snapshot. */
function TopCharts({ title, snaps }: { title: string; snaps: Record<(typeof TIME_RANGES)[number], TopSnap> }) {
  const yesterday = daysAgo(1);
  return (
    <>
      <h2 className="sec">{title}</h2>
      <div className="ranges all-external">
        {TIME_RANGES.map((range) => {
          const snap = snaps[range];
          return (
            <section className="range" key={range}>
              <h3 className="rlabel">
                {RANGE_LABEL[range]}
                {snap.capturedOn && snap.capturedOn < yesterday ? `, ${shortDate(snap.capturedOn)}` : ''}
              </h3>
              {snap.entries.length > 0 ? (
                <ol className="chart">
                  {snap.entries.slice(0, 10).map((e) => (
                    <li key={`${range}-${e.rank}`}>
                      <span className="rank tnum">{e.rank}</span>
                      <span className="cname">
                        {e.url ? <a href={e.url} target="_blank" rel="noreferrer">{e.name}</a> : e.name}
                      </span>
                      {e.detail && <span className="cdetail">{e.detail}</span>}
                    </li>
                  ))}
                </ol>
              ) : (
                <p className="empty">Not collected yet.</p>
              )}
            </section>
          );
        })}
      </div>
    </>
  );
}

function daysSince(iso: string): number {
  return Math.max(0, Math.floor((Date.now() - new Date(iso).getTime()) / 86_400_000));
}

export default async function MusicPage() {
  const [summary, recent, listening, tops] = await Promise.all([
    getSummary(),
    getRecentPlays(60),
    getListening(60),
    getLatestTops(),
  ]);

  const collectingDays = summary.since ? daysSince(summary.since) : null;
  /* The same line the hub row prints: a collector running cleanly with nothing to collect looks
   * like a broken one from outside, so the age of the newest play is stated once it means something. */
  const newestAgeDays = summary.latest ? daysSince(summary.latest) : null;
  const live = summary.liveness;

  return (
    <div className="music">
      {/* See /curio: this page had no h1 either. */}
      <h1>Music</h1>

      {/* TWO CONDITIONS, TWO NOTICES, since 2026-08-28:
        *
        *   1. The COLLECTOR is stale. Plays are being lost right now. The alarm.
        *   2. A run in the last 7 days SATURATED: it returned the full 50 and plays between runs are
        *      already gone (05-small-apps M1). Matched on its own phrase, not on "the run had a
        *      warning", and held for 7 days rather than cleared by the next clean run.
        *
        * The third one, a failed render-time now-playing probe, went with the server fetch: the
        * client component shows nothing when Spotify is quiet or unreachable, and a dead token
        * reaches notice 1 within 36 hours. */}
      {live.stale && (
        <div className="alarm">
          <strong>The collector is not working.</strong>{' '}
          {live.lastOkAt
            ? `Last successful run was ${timeAgo(live.lastOkAt)}.`
            : 'It has never completed a successful run.'}{' '}
          Plays are being lost while this is true, and they cannot be recovered later.
          {live.lastError && <span className="why">{failureLabel(live.lastError)}</span>}
        </div>
      )}

      {live.lostPlaysAt && (
        <div className="alarm">
          <strong>Some plays were lost between runs</strong>, {timeAgo(live.lostPlaysAt)}.
        </div>
      )}

      {/* `all-external`: every link on this page goes to Spotify, so the per-link "leaves the
        * site" marker declared in globals.css would print thirty times and say nothing. */}
      <div className="all-external">
        <NowPlaying />
      </div>

      <div className="stat">
        <span className="live tnum">{summary.plays}</span> plays collected
        <span className="dot">·</span>
        <span className="live tnum">{summary.tracks}</span> tracks
        <span className="dot">·</span>
        <span className="live tnum">{summary.artists}</span> artists
        {summary.since && (
          <>
            <span className="dot">·</span>
            since {shortDate(dayOf(summary.since))}
            {collectingDays !== null && collectingDays < 1 ? ', today' : ''}
          </>
        )}
      </div>
      {newestAgeDays !== null && newestAgeDays >= 2 && (
        <p className="stat">nothing new for {newestAgeDays} days</p>
      )}

      {/* ---------------------------------------------------------------- pictures, 2026-09-27
          His ask: "just lists of songs ... something more graphic". The lists below are folded, not
          deleted; the pictures come first. All of it from our own collected plays. Minutes are
          track lengths (a skip counts whole), so the labels say "track". */}
      {listening.totalMinutes > 0 && (
        <>
          {/* Two to a line on a wide screen (music.css `.board`); one column, this order, on a phone.
              Readout: tap a cell or a bar for its minutes. */}
          <div className="board">
            <section>
              <h2 className="sec">When I listen</h2>
              <p className="stat">
                <span className="tnum">{Math.round(listening.totalMinutes / 60)}</span> track hours, {lastDays(listening.days)}
              </p>
              <Readout><ListeningClock clock={listening.clock} /></Readout>
            </section>
            <section>
              <h2 className="sec">Every day</h2>
              <p className="stat">track minutes, {lastDays(listening.perDay.length)}</p>
              <Readout><MinutesPerDay perDay={listening.perDay} /></Readout>
            </section>
          </div>

          <div className="board">
            <section>
              <h2 className="sec">On repeat</h2>
              <p className="stat">plays, {lastDays(listening.days)}</p>
              <AlbumWall albums={listening.albums} />
            </section>
            <section>
              <h2 className="sec">Most played</h2>
              <p className="stat">plays, {lastDays(listening.days)}</p>
              <ArtistBars artists={listening.artists} />
            </section>
          </div>
        </>
      )}

      <details className="more">
        <summary>Spotify&apos;s charts</summary>
        <TopCharts title="Top tracks" snaps={tops.track} />
        <TopCharts title="Top artists" snaps={tops.artist} />
      </details>

      <details className="more">
        <summary>Recently played</summary>
        {recent.length > 0 ? (
          <div className="plays all-external">{recent.map(Play)}</div>
        ) : (
          <p className="empty">Nothing collected yet.</p>
        )}
      </details>

    </div>
  );
}
